### ISSUE TITLE
Streaming

### ISSUE THREAD

**Issue by audvin** [dissorial/doc-chatbot#11]
Would love to see streaming support here, is that something that is on the roadmap shortly or far out?

https://blog.langchain.dev/streaming-support-in-langchain/

**Comment by dissorial** [comment]
Yes, it's on the roadmap -- in fact, as one of the next few features.

**Comment by audvin** [comment]
That's exciting to hear!

**Comment by dissorial** [comment]
I've looked into this but it seems like Conversational Retrieval QA Chain does not support streaming as of now. LangChain of course does support streaming responses in general, but to integrate it into this app, I'd have to rework the entire setup of the llm model and its chain. Streaming is great and I'd definitely love to have it as a feature, but given the above, it will probably take some time before I get to it.
