### ISSUE TITLE
Add support for local LLMs? (Vicuna et al?)

### ISSUE THREAD

**Issue by jasmeetchadha** [dissorial/doc-chatbot#12]
Thanks!

**Comment by dissorial** [comment]
Know of any solid JS guide on how to do this? I've tested local LLMs but only with Python.

**Comment by jasmeetchadha** [comment]
Unfortunately I don’t know. I have also seen them done in Python

**Comment by dissorial** [comment]
I can't promise it'll be added any time soon but I'll definitely have a look into it as I plan to expand the features of this app to make it more versatile over time. Thank you for the suggestion!
