### ISSUE TITLE
Callback redirection OAuth2

### ISSUE THREAD

**Issue by rickyurvina** [dissorial/doc-chatbot#13]
Hey, thanks for share your project. I was testing but I cannot login. I generated Google client id and secret and configure the redirect URL in the credentials as http://localhost:3000/settings. Is it right? I would appreciate If you can help me your test your app.

Regrets...

**Comment by dissorial** [comment]
That's not quite the right configuration. I shared more details in here #10, where I wrote:

              Okay, verify the following:

**In google developer console**
- In the credentials section, 'Authorized JavaScript origins' should be set to http://localhost:3000
- in the credentials section, 'Authorized redirect URIs' should be set to http://localhost:3000/api/auth/callback/google
- in OAuth consent screen, you added your email address to 'Test users'

**In .env file**
- you set both your `GOOGLE_CLIENT_ID` and `GOOGLE_CLIENT_SECRET`, and they are both without quotation marks
- `ALLOWED_EMAIL_DOMAIN` is set correctly (this should not be your email, but a domain like @google.com, @yahoo.com, etc.)
- `NEXTAUTH_URL` is equal to `http://localhost:3000`

_Originally posted by @dissorial in https://github.com/dissorial/doc-chatbot/issues/10#issuecomment-1548417106_

**Comment by dissorial** [comment]
@rickyurvina readme has now been updated to include more details about setting up google auth
