### ISSUE TITLE
storage location / system prompt / web app?  

### ISSUE THREAD

**Issue by jasmeetchadha** [dissorial/doc-chatbot#15]
1. where are the documents / pdf stored currently after we upload them via browser? 

2. Where can I look at / change system prompt for OpenAI QA? 

3. Would it be possible for you to share a little guide on how to host this web app so that it can be accessed via browser anywhere? (Currently running locally). Sorry I am not a coder but able to Lego build this 

thanks very much for your help so far!

**Comment by dissorial** [comment]
1. If you're running this locally, the documents are first uploaded to `tmp` folder in the root directory. Then, after you 'Ingest' them, they are deleted.
2. In `makeChain.ts`, which is located in the `utils` folder
3. Yes, I'll add it to readme.md soon.
