### ISSUE TITLE
Sharing of Namespaces between Google accounts

### ISSUE THREAD

**Issue by ollieanwyll** [dissorial/doc-chatbot#18]
Hey, awesome project. Keep up the great work!

Ideally, i'd like to create Namespaces to be shared between all users. Is this possible now? or would it need to be a feature?

Also, if it was possible to have admin accounts and limit creation of Namespaces to admins, i'd for sure use that feature.

Cheers.

**Comment by dissorial** [comment]
Hi,

when you say `shared between all users`, what users are you referring to here? Some people from your organization or company?

Regarding the admin accounts and limitng creation of namespaces -- sounds like a reasonable feature to me, but probably not something that makes sense to develop as standalone feature. 

I think it'd have to be a part of some larger update that allows people to create some sort of a 'hierarchy' in the user base to decide who the admin is, who can ingest files and create namespaces, and so on. Doable, and certainly useful to some, but also something that would require a significant amount of time, which I can't afford to spend on it at this moment.

**Comment by ollieanwyll** [comment]
Hey,

I meant any user that's been able to sign the application via Google. In my case though, anyone within my Google organisation would enable what I'm trying to achieve.

Fully understand on the whole admin/hierarchy side of things. Just a feature suggestion.

Thanks again for the awesome work.

**Comment by dissorial** [comment]
Fully understood, and I do agree that it'd be a nice feature to add down the line :) Thank you again!
