### ISSUE TITLE
Issue running npx netauth jwt-secret

### ISSUE THREAD

**Issue by kevinbaroro** [dissorial/doc-chatbot#19]
Hi, I tried to follow the instruction for running "npx netauth jwt-secret" which causing an error

AzureAD+KevinClaytonBaroro@DESKTOP-SVJE8CL MINGW64 ~/doc-chatbot (master)
$ npx netauth jwt-secret
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/netauth - Not found
npm ERR! 404
npm ERR! 404  'netauth@*' is not in this registry.
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in: C:\Users\User\AppData\Local\npm-cache\_logs\2023-05-17T15_15_52_219Z-debug-0.log

May you have the fix for this?

**Comment by dissorial** [comment]
If it doesn't work, try running `openssl rand -base64 32` in git bash
