### ISSUE TITLE
Invalid PDF structure - Failed to Ingest

### ISSUE THREAD

**Issue by ollieanwyll** [dissorial/doc-chatbot#20]
I accidentally tried to upload a PDF that was corrupt. Now I can't seem to ingest any PDFs at all. I've tried recreating the Pinecode DB and also cleared out the Namespaces from Mongo. I'm going to try rebuilding everything and will update this issue, but just wanted to highlight it. Cheers!

**Comment by ollieanwyll** [comment]
UPDATE: It turns out I had a load of PDFs in the /tmp dir. After clearing those out, all seems to be working again.

**Comment by dissorial** [comment]
Glad you solved it!
