### ISSUE TITLE
npx nextauth secret error

### ISSUE THREAD

**Issue by spectramaster** [dissorial/doc-chatbot#21]
When I tried to generate secret using command  "npx nextauth secret" and  "npx nextauth jwt-secret", the output seems to indicate there is no such npm module named 'nextauth'.

ERROR1(Execute npx nextauth secret):

npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/nextauth - Not found
npm ERR! 404 
npm ERR! 404  'nextauth@*' is not in this registry.
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ai/.npm/_logs/2023-05-18T08_37_34_893Z-debug-0.log

____________________________________________________________________________________________________

ERROR2(Execute npx nextauth jwt-secret):

npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/nextauth - Not found
npm ERR! 404 
npm ERR! 404  'nextauth@*' is not in this registry.
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ai/.npm/_logs/2023-05-18T08_39_35_623Z-debug-0.log

**Comment by dissorial** [comment]
I update this section in generating secrets in the readme file. If that gives you an error, generate it by running `openssl rand -base64 32` in Git Bash
