### ISSUE TITLE
Support multiple files in one pinecone namespace

### ISSUE THREAD

**Issue by kevinbaroro** [dissorial/doc-chatbot#23]
Hi @dissorial, is it easy to add a feature where we can upload multiple files as one namespace? Btw. This upgraded code of yours help's me a lot in my R&D. Thank you.

**Comment by dissorial** [comment]
Hi, thank you for the nice words. Yes, this app currently supports that. You should be able to just select and upload any number of files you want when the upload window opens. Or is that not working for you?

**Comment by kevinbaroro** [comment]
It's all good now. Thank you.
