### ISSUE TITLE
Web app authentication issues

### ISSUE THREAD

**Issue by jasmeetchadha** [dissorial/doc-chatbot#32]
Hi Dissorial 

thanks for all the work. I am now trying to run the app on vercel. 

I copied from your git 
Changed the env file with api secrets I was using on desktop 
Changed url to webapp url 

I am getting an authentication error. Not sure why? I am using the next auth secret that I generated on desktop. Could this be? How would I generate next auth secret I’m vercel? 

I have added the user in Google api console but it says access denied.

Any idea what might be causing this?

![IMG_0623](https://github.com/dissorial/doc-chatbot/assets/49923268/95d385e4-a719-48eb-b2f4-5634d687e528)

**Comment by jasmeetchadha** [comment]
![Uploading IMG_0624.jpeg…]()

**Comment by hjhaooo** [comment]
Go to your google cloud console and set the allowance of your custom domain.
APIs and Services -> Credentials -> OAuth 2.0 Client IDs -> edit OAuth client -> Authorized JavaScript origins and Authorized redirect URIs

**Comment by jasmeetchadha** [comment]
Those were set already

JS origins
https://xxxxxx.vercel.app

Authorised redirect
https://xxxx.vercel.app/api/auth/callback/google

**Comment by jasmeetchadha** [comment]
Thats sorted now. I had to promote deployment to production so the correct URL's are active. 

Now after login using the profile I was prev using from local
1) I dont see past namespaces
2) When uploading new document, it doesnt ingest. I get an error: Unexpected token 'A', "An error o"... is not valid JSON
